# Generated by Django 5.1.5 on 2025-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamgem', models.ImageField(upload_to='upload/%y%m%d/')),
                ('criado_em', models.DateTimeField()),
            ],
        ),
    ]
